version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: jo-news-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  dagster:
    build: .
    container_name: jo-news-dagster
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SCRAPER_LIMIT: ${SCRAPER_LIMIT}
    ports:
      - "${DAGSTER_PORT}:3000"
    volumes:
      - ./dagster_home:/opt/dagster/home
      - ./src:/app/src
    command: ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000", "-m", "src.definitions"]
